#!/usr/bin/env node
/**
 * Dump the local database's posts as SQL, for loading into a remote D1.
 *
 * The import (scripts/import-markdown.mjs) runs against a local dev server,
 * because that is where the markdown files are and where the CLI can convert
 * them without an auth round trip. What comes out is a local SQLite file — and
 * the deployed site reads D1. This bridges the two.
 *
 * It is a one-way push, and it replaces rather than merges: posts, their
 * revisions, the tag terms and the tag assignments are deleted on the far side
 * and rewritten from here. That is only safe while the local copy is the
 * authority, which is true exactly once — during the migration, before anyone
 * has written a post in the deployed admin panel. After that, the database is
 * the authority and this script is a foot-gun; it stays for the record and for
 * standing a second instance up from scratch.
 *
 *   node scripts/export-content.mjs > scripts/out/content.sql
 *   npx wrangler d1 execute seanbehan-ca --remote --file scripts/out/content.sql
 */

import Database from 'better-sqlite3';
import { readdirSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const D1_DIR = join(ROOT, '.wrangler/state/v3/d1/miniflare-D1DatabaseObject');

const files = readdirSync(D1_DIR).filter((f) => f.endsWith('.sqlite') && f !== 'metadata.sqlite');
if (files.length !== 1) {
	throw new Error(`expected one D1 sqlite file in ${D1_DIR}, found ${files.length}`);
}

const db = new Database(join(D1_DIR, files[0]), { readonly: true });

const literal = (value) => {
	if (value === null || value === undefined) return 'NULL';
	if (typeof value === 'number') return String(value);
	if (Buffer.isBuffer(value)) return `X'${value.toString('hex')}'`;
	return `'${String(value).replace(/'/g, "''")}'`;
};

const insert = (table, row) =>
	`INSERT INTO ${table} (${Object.keys(row).join(', ')}) VALUES (${Object.values(row)
		.map(literal)
		.join(', ')});`;

const out = [];
const say = (line) => out.push(line);

say('-- Generated by scripts/export-content.mjs. Replaces the posts on the far side.');

/*
 * Order is load-bearing, and `PRAGMA defer_foreign_keys` does not save it: D1
 * runs a file as a sequence of statements rather than one deferred
 * transaction, so every foreign key is checked as it is written.
 *
 * An entry points at the revision holding its live body (ec_posts
 * .live_revision_id), so the revisions go in first. Coming the other way, the
 * assignments point at both an entry and a term, so they are cleared first.
 */
say('DELETE FROM content_taxonomies;');
say('DELETE FROM ec_posts;');
say("DELETE FROM revisions WHERE collection = 'posts';");
say("DELETE FROM taxonomies WHERE name = 'tag';");

for (const term of db.prepare("SELECT * FROM taxonomies WHERE name = 'tag' ORDER BY slug").all()) {
	say(insert('taxonomies', term));
}

/**
 * `author_id` is dropped rather than carried across: it points at the dev-bypass
 * user this machine created, which does not exist on the deployed site. The
 * posts have a byline through the seed; the author column is provenance, and
 * pointing it at a missing row is worse than leaving it empty.
 */
const posts = db
	.prepare('SELECT * FROM ec_posts WHERE deleted_at IS NULL ORDER BY published_at')
	.all();

const ids = new Set(posts.map((post) => post.id));

for (const revision of db.prepare("SELECT * FROM revisions WHERE collection = 'posts'").all()) {
	if (!ids.has(revision.entry_id)) continue;
	say(insert('revisions', { ...revision, author_id: null }));
}

for (const post of posts) {
	say(insert('ec_posts', { ...post, author_id: null }));
}

for (const row of db.prepare("SELECT * FROM content_taxonomies WHERE collection = 'posts'").all()) {
	if (!ids.has(row.entry_id)) continue;
	say(insert('content_taxonomies', row));
}

// The search index is an external-content FTS5 table over ec_posts, so it is
// not copied — it is rebuilt from the rows just written.
say("INSERT INTO _emdash_fts_posts(_emdash_fts_posts) VALUES('rebuild');");

console.log(out.join('\n'));
console.error(`export: ${posts.length} posts, ${out.length} statements`);
